services:
  jellyfin-helper-ro:
    build: .
    image: jellyfin-helper-ro
    container_name: jellyfin-helper-ro
    restart: "no"
    env_file: .env
    volumes:
      - /path/to/your/movies:/media/movies:rw
      - /path/to/your/tv-shows:/media/shows:rw
      - ./data:/app/data:rw
